# Generated by Django 4.0 on 2022-02-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210310_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Datos De Poblacion'},
        ),
        migrations.RenameField(
            model_name='countrydata',
            old_name='country',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='countrydata',
            old_name='population',
            new_name='poblacion',
        ),
    ]
