# Generated by Django 4.0 on 2022-02-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_countrydata_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryData',
            new_name='PaisData',
        ),
    ]
