# Generated by Django 4.0 on 2022-02-08 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_countrydata_paisdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagio', models.IntegerField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paisdata')),
            ],
            options={
                'verbose_name_plural': 'Contagios De Poblacion',
            },
        ),
    ]
