# Generated by Django 4.0 on 2022-02-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_coviddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coviddata',
            old_name='contagio',
            new_name='contagios',
        ),
    ]
